### ISSUE TITLE
allow users/players to delete themself

### ISSUE THREAD

**Issue by Licenser** [Licenser/orgtool2#8]
Users should be able to delete themself.

**Comment by skoma** [comment]
Also deactivated users should be able to read themselfs.

[info] GET /api/users/2
...
[debug] OrgtoolDb.UserApiController halted in Guardian.Plug.EnsurePermissions.call/2

**Comment by Licenser** [comment]
Hmm I disagree on that, it's common practice for pages that require activation that you often can't even log in until your account has been confirmed

**Comment by Licenser** [comment]
I'll close this as the ticket itself is done, the discussion how to treat deactivated users is a different one.
